// AI Data Engineering System - Export Utilities

import jsPDF from 'jspdf';

// Types
export interface ExportableContent {
  title: string;
  type: 'architecture' | 'pipeline' | 'transformation' | 'dashboard' | 'report';
  sections: ExportSection[];
  metadata?: {
    project?: string;
    industry?: string;
    date?: string;
    author?: string;
  };
}

export interface ExportSection {
  title: string;
  content: string;
  code?: string;
  language?: string;
}

export interface ExportedFile {
  name: string;
  content: Buffer | string;
  mimeType: string;
}

// PDF Generator
export class PDFGenerator {
  private doc: jsPDF;
  private yPosition: number;
  private pageHeight: number;
  private pageWidth: number;
  private margin: number;

  constructor() {
    this.doc = new jsPDF();
    this.pageHeight = this.doc.internal.pageSize.height;
    this.pageWidth = this.doc.internal.pageSize.width;
    this.margin = 20;
    this.yPosition = this.margin;
  }

  // Add title page
  addTitlePage(title: string, metadata?: ExportableContent['metadata']): void {
    // Title
    this.doc.setFontSize(28);
    this.doc.setTextColor(30, 41, 59);
    this.yPosition = 60;
    this.doc.text(title, this.pageWidth / 2, this.yPosition, { align: 'center' });

    // Metadata
    if (metadata) {
      this.doc.setFontSize(12);
      this.doc.setTextColor(100, 116, 139);
      
      if (metadata.project) {
        this.yPosition += 20;
        this.doc.text(`Project: ${metadata.project}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
      }
      if (metadata.industry) {
        this.yPosition += 10;
        this.doc.text(`Industry: ${metadata.industry}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
      }
      if (metadata.date) {
        this.yPosition += 10;
        this.doc.text(`Date: ${metadata.date}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
      }
      if (metadata.author) {
        this.yPosition += 10;
        this.doc.text(`Generated by: ${metadata.author}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
      }
    }

    // Footer
    this.doc.setFontSize(10);
    this.doc.setTextColor(148, 163, 184);
    this.doc.text(
      'AI Data Engineering System - Generated Document',
      this.pageWidth / 2,
      this.pageHeight - 20,
      { align: 'center' }
    );

    this.addNewPage();
  }

  // Add section
  addSection(section: ExportSection): void {
    this.checkPageBreak(40);

    // Section title
    this.doc.setFontSize(16);
    this.doc.setTextColor(30, 41, 59);
    this.doc.text(section.title, this.margin, this.yPosition);
    this.yPosition += 10;

    // Section content
    this.doc.setFontSize(11);
    this.doc.setTextColor(51, 65, 85);
    
    const lines = this.doc.splitTextToSize(section.content, this.pageWidth - 2 * this.margin);
    
    for (const line of lines) {
      this.checkPageBreak(10);
      this.doc.text(line, this.margin, this.yPosition);
      this.yPosition += 6;
    }

    // Code block if present
    if (section.code) {
      this.yPosition += 5;
      this.addCodeBlock(section.code, section.language);
    }

    this.yPosition += 10;
  }

  // Add code block
  private addCodeBlock(code: string, language?: string): void {
    this.checkPageBreak(40);

    // Background for code
    const codeLines = this.doc.splitTextToSize(code, this.pageWidth - 2 * this.margin - 10);
    const blockHeight = codeLines.length * 5 + 10;

    this.doc.setFillColor(30, 41, 59);
    this.doc.roundedRect(
      this.margin,
      this.yPosition,
      this.pageWidth - 2 * this.margin,
      blockHeight,
      3,
      3,
      'F'
    );

    // Language label
    if (language) {
      this.doc.setFontSize(8);
      this.doc.setTextColor(148, 163, 184);
      this.doc.text(language.toUpperCase(), this.margin + 5, this.yPosition + 6);
    }

    // Code text
    this.doc.setFontSize(9);
    this.doc.setTextColor(226, 232, 240);
    
    let codeY = this.yPosition + (language ? 15 : 8);
    for (const line of codeLines) {
      this.doc.text(line, this.margin + 5, codeY);
      codeY += 5;
    }

    this.yPosition += blockHeight + 5;
  }

  // Check if need new page
  private checkPageBreak(requiredSpace: number): void {
    if (this.yPosition + requiredSpace > this.pageHeight - this.margin) {
      this.addNewPage();
    }
  }

  // Add new page
  private addNewPage(): void {
    this.doc.addPage();
    this.yPosition = this.margin;
  }

  // Add table of contents
  addTableOfContents(sections: ExportSection[]): void {
    this.doc.setFontSize(18);
    this.doc.setTextColor(30, 41, 59);
    this.doc.text('Table of Contents', this.margin, this.yPosition);
    this.yPosition += 15;

    this.doc.setFontSize(12);
    this.doc.setTextColor(51, 65, 85);

    sections.forEach((section, index) => {
      this.doc.text(`${index + 1}. ${section.title}`, this.margin + 10, this.yPosition);
      this.yPosition += 8;
    });

    this.addNewPage();
  }

  // Generate PDF
  generate(): Buffer {
    return Buffer.from(this.doc.output('arraybuffer'));
  }
}

// Generate architecture PDF
export async function generateArchitecturePDF(data: {
  projectName: string;
  industry?: string;
  architecture: {
    warehouseType: string;
    orchestrationTool: string;
    transformationFramework: string;
    biTool?: string;
    pattern: string;
    diagrams?: string[];
    rationale?: string;
    costEstimate?: {
      monthly: number;
      breakdown: Record<string, number>;
    };
  };
}): Promise<Buffer> {
  const pdf = new PDFGenerator();

  pdf.addTitlePage('Architecture Design Document', {
    project: data.projectName,
    industry: data.industry,
    date: new Date().toLocaleDateString(),
    author: 'AI Data Engineering System',
  });

  // Overview section
  pdf.addSection({
    title: '1. Architecture Overview',
    content: `This document outlines the recommended data architecture for ${data.projectName}. The architecture has been designed based on industry best practices and project-specific requirements.`,
  });

  // Technology Stack
  pdf.addSection({
    title: '2. Technology Stack',
    content: `
Data Warehouse: ${data.architecture.warehouseType}
Orchestration: ${data.architecture.orchestrationTool}
Transformation: ${data.architecture.transformationFramework}
BI Tool: ${data.architecture.biTool || 'Not specified'}
Architecture Pattern: ${data.architecture.pattern}
    `.trim(),
  });

  // Rationale
  if (data.architecture.rationale) {
    pdf.addSection({
      title: '3. Design Rationale',
      content: data.architecture.rationale,
    });
  }

  // Cost Estimate
  if (data.architecture.costEstimate) {
    const breakdown = Object.entries(data.architecture.costEstimate.breakdown)
      .map(([key, value]) => `  - ${key}: $${value}/month`)
      .join('\n');

    pdf.addSection({
      title: '4. Cost Estimation',
      content: `
Monthly Estimated Cost: $${data.architecture.costEstimate.monthly}

Breakdown:
${breakdown}
      `.trim(),
    });
  }

  // Diagrams
  if (data.architecture.diagrams && data.architecture.diagrams.length > 0) {
    pdf.addSection({
      title: '5. Architecture Diagrams',
      content: 'The following diagrams illustrate the proposed architecture:',
      code: data.architecture.diagrams[0],
      language: 'mermaid',
    });
  }

  return pdf.generate();
}

// Generate pipeline code ZIP
export async function generatePipelineZip(data: {
  projectName: string;
  pipelines: Array<{
    name: string;
    type: string;
    code: string;
    language: string;
  }>;
  transformations?: Array<{
    name: string;
    sql: string;
  }>;
  configs?: Array<{
    name: string;
    content: string;
    format: string;
  }>;
}): Promise<Buffer> {
  const archiver = (await import('archiver')).default;
  
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on('data', (chunk) => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);

    // Create folder structure
    const projectSlug = data.projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');

    // Add pipelines
    data.pipelines.forEach((pipeline) => {
      const ext = pipeline.language === 'python' ? 'py' : pipeline.language;
      archive.append(Buffer.from(pipeline.code), {
        name: `${projectSlug}/pipelines/${pipeline.name}.${ext}`,
      });
    });

    // Add transformations
    if (data.transformations) {
      data.transformations.forEach((t) => {
        archive.append(Buffer.from(t.sql), {
          name: `${projectSlug}/transformations/${t.name}.sql`,
        });
      });
    }

    // Add configs
    if (data.configs) {
      data.configs.forEach((config) => {
        const ext = config.format === 'yaml' ? 'yml' : config.format;
        archive.append(Buffer.from(config.content), {
          name: `${projectSlug}/config/${config.name}.${ext}`,
        });
      });
    }

    // Add README
    const readme = `# ${data.projectName} - Generated Pipelines

This folder contains automatically generated data pipelines and transformations.

## Structure

- \`pipelines/\` - ETL/ELT pipeline code
- \`transformations/\` - SQL transformation models
- \`config/\` - Configuration files

## Getting Started

1. Review each pipeline file
2. Configure connections in config files
3. Deploy using your orchestration tool

Generated by AI Data Engineering System
`;
    archive.append(Buffer.from(readme), {
      name: `${projectSlug}/README.md`,
    });

    archive.finalize();
  });
}

// Generate project report PDF
export async function generateProjectReportPDF(project: {
  name: string;
  description?: string;
  status: string;
  industry?: string;
  deliverables: Array<{
    type: string;
    name: string;
    content: string;
  }>;
}): Promise<Buffer> {
  const pdf = new PDFGenerator();

  pdf.addTitlePage('Project Report', {
    project: project.name,
    industry: project.industry,
    date: new Date().toLocaleDateString(),
    author: 'AI Data Engineering System',
  });

  pdf.addSection({
    title: '1. Project Overview',
    content: `
Project: ${project.name}
Status: ${project.status}
Industry: ${project.industry || 'Not specified'}

${project.description || 'No description provided.'}
    `.trim(),
  });

  // Deliverables
  project.deliverables.forEach((deliverable, index) => {
    pdf.addSection({
      title: `${index + 2}. ${deliverable.name}`,
      content: deliverable.content.slice(0, 2000), // Limit content
    });
  });

  return pdf.generate();
}
