'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Progress } from '@/components/ui/progress'
import { 
  Database, 
  Cpu, 
  Shield, 
  BarChart3, 
  Play, 
  CheckCircle2, 
  Clock,
  TrendingUp,
  Users,
  ShoppingCart,
  CreditCard,
  Building2,
  Zap,
  GitBranch,
  Settings,
  ArrowRight,
  Loader2,
  FileText,
  Code2,
  PieChart
} from 'lucide-react'

// Demo Company Data
const COMPANY = {
  name: 'TechMart',
  industry: 'E-Commerce & Retail Tech',
  description: 'Retailer en ligne spécialisé dans les produits technologiques',
  employees: 250,
  revenue: '45M€',
  dataSources: [
    { id: 1, name: 'PostgreSQL - Production DB', type: 'postgresql', tables: 47, columns: 312, status: 'connected' },
    { id: 2, name: 'Shopify - Marketplace', type: 'shopify', tables: 12, columns: 85, status: 'connected' },
    { id: 3, name: 'Google Analytics 4', type: 'ga4', tables: 8, columns: 45, status: 'connected' },
    { id: 4, name: 'Google Ads', type: 'google_ads', tables: 6, columns: 32, status: 'connected' },
    { id: 5, name: 'Stripe - Payments', type: 'stripe', tables: 15, columns: 78, status: 'connected' },
  ],
  objectives: [
    { title: '360° Customer View', description: 'Vue unifiée du client tous canaux', status: 'in_progress' },
    { title: 'Inventory Optimization', description: 'Réduction ruptures de stock de 40%', status: 'pending' },
    { title: 'Marketing Attribution', description: 'ROI marketing multi-canal', status: 'pending' },
    { title: 'Churn Prediction', description: 'Identification clients à risque', status: 'pending' },
  ]
}

// Agent Execution Simulation
const AGENTS = [
  { id: 'discovery', name: 'Data Archaeologist', icon: Database, description: 'Découverte et profilage des données', status: 'idle', progress: 0 },
  { id: 'architecture', name: 'Blueprint Designer', icon: Building2, description: 'Design de l\'architecture data', status: 'idle', progress: 0 },
  { id: 'pipeline', name: 'Flow Builder', icon: GitBranch, description: 'Génération des pipelines ETL', status: 'idle', progress: 0 },
  { id: 'transformation', name: 'Data Alchemist', icon: Cpu, description: 'Transformations et modélisation', status: 'idle', progress: 0 },
  { id: 'bi', name: 'Visual Storyteller', icon: BarChart3, description: 'Dashboards et KPIs', status: 'idle', progress: 0 },
]

// Pipeline Results
const PIPELINE_RESULTS = {
  tables: 47,
  models: 23,
  dags: 5,
  tests: 45,
  linesOfCode: 2847,
  executionTime: '14 jours',
}

// Generated Code Sample
const SAMPLE_DBT_MODEL = `
-- Generated by DataSphere Innovation AI Agent
-- Model: customers_360
-- Description: Vue 360° du client

{{ config(
    materialized='table',
    schema='marts',
    tags=['customer', '360-view']
) }}

WITH customer_base AS (
    SELECT 
        c.customer_id,
        c.email,
        c.first_name,
        c.last_name,
        c.created_at as customer_since,
        c.segment
    FROM {{ source('postgres', 'customers') }} c
),

shopify_customers AS (
    SELECT 
        customer_id,
        COUNT(DISTINCT order_id) as shopify_orders,
        SUM(total_price) as shopify_revenue,
        AVG(total_price) as avg_order_value
    FROM {{ source('shopify', 'orders') }}
    GROUP BY 1
),

stripe_customers AS (
    SELECT 
        customer_id,
        COUNT(DISTINCT invoice_id) as stripe_invoices,
        SUM(amount) as stripe_revenue,
        MAX(created_at) as last_payment
    FROM {{ source('stripe', 'invoices') }}
    GROUP BY 1
),

ga4_customers AS (
    SELECT 
        user_id as customer_id,
        COUNT(DISTINCT session_id) as sessions,
        AVG(session_duration) as avg_session_duration,
        SUM(page_views) as total_page_views
    FROM {{ source('ga4', 'sessions') }}
    GROUP BY 1
)

SELECT 
    cb.customer_id,
    cb.email,
    cb.first_name,
    cb.last_name,
    cb.customer_since,
    cb.segment,
    
    -- Shopify metrics
    COALESCE(sc.shopify_orders, 0) as shopify_orders,
    COALESCE(sc.shopify_revenue, 0) as shopify_revenue,
    COALESCE(sc.avg_order_value, 0) as avg_order_value,
    
    -- Stripe metrics  
    COALESCE(stc.stripe_invoices, 0) as stripe_invoices,
    COALESCE(stc.stripe_revenue, 0) as stripe_revenue,
    stc.last_payment,
    
    -- GA4 metrics
    COALESCE(ga.sessions, 0) as web_sessions,
    COALESCE(ga.avg_session_duration, 0) as avg_session_duration,
    COALESCE(ga.total_page_views, 0) as total_page_views,
    
    -- Computed metrics
    COALESCE(sc.shopify_revenue, 0) + COALESCE(stc.stripe_revenue, 0) as total_revenue,
    CURRENT_DATE - cb.customer_since as customer_age_days

FROM customer_base cb
LEFT JOIN shopify_customers sc ON cb.customer_id = sc.customer_id
LEFT JOIN stripe_customers stc ON cb.customer_id = stc.customer_id
LEFT JOIN ga4_customers ga ON cb.customer_id = ga.customer_id
`

export default function DemoPage() {
  const [activeTab, setActiveTab] = useState('overview')
  const [agents, setAgents] = useState(AGENTS)
  const [isRunning, setIsRunning] = useState(false)
  const [currentPhase, setCurrentPhase] = useState(0)
  const [results, setResults] = useState<typeof PIPELINE_RESULTS | null>(null)
  const [qualityScore, setQualityScore] = useState(72)

  // Simulate agent execution
  const runDemo = async () => {
    setIsRunning(true)
    setResults(null)
    setCurrentPhase(0)
    
    // Reset agents
    setAgents(AGENTS.map(a => ({ ...a, status: 'idle', progress: 0 })))

    // Simulate each agent
    for (let i = 0; i < agents.length; i++) {
      setCurrentPhase(i + 1)
      
      // Update agent to running
      setAgents(prev => prev.map((a, idx) => 
        idx === i ? { ...a, status: 'running', progress: 0 } : a
      ))

      // Simulate progress
      for (let p = 0; p <= 100; p += 10) {
        await new Promise(r => setTimeout(r, 100))
        setAgents(prev => prev.map((a, idx) => 
          idx === i ? { ...a, progress: p } : a
        ))
      }

      // Update agent to completed
      setAgents(prev => prev.map((a, idx) => 
        idx === i ? { ...a, status: 'completed', progress: 100 } : a
      ))
    }

    // Simulate quality score improvement
    setQualityScore(94)
    
    // Show results
    setResults(PIPELINE_RESULTS)
    setIsRunning(false)
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
      <div className="container mx-auto p-6 space-y-8">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-white">Démonstration TechMart</h1>
            <p className="text-slate-400">Cas d'usage: Plateforme E-Commerce Tech</p>
          </div>
          <div className="flex items-center gap-4">
            <Badge variant="outline" className="border-green-500/50 text-green-400">
              <CheckCircle2 className="h-3 w-3 mr-1" />
              Sources connectées: 5/5
            </Badge>
            <Button 
              onClick={runDemo} 
              disabled={isRunning}
              className="bg-gradient-to-r from-blue-600 to-purple-600"
            >
              {isRunning ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Exécution en cours...
                </>
              ) : (
                <>
                  <Play className="h-4 w-4 mr-2" />
                  Lancer la démo
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Company Overview */}
        <div className="grid md:grid-cols-4 gap-4">
          <Card className="bg-slate-900/50 border-slate-800/50">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <Building2 className="h-8 w-8 text-purple-500" />
                <div>
                  <p className="text-2xl font-bold text-white">{COMPANY.name}</p>
                  <p className="text-sm text-slate-400">{COMPANY.industry}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-slate-900/50 border-slate-800/50">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <Users className="h-8 w-8 text-blue-500" />
                <div>
                  <p className="text-2xl font-bold text-white">{COMPANY.employees}</p>
                  <p className="text-sm text-slate-400">Employés</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-slate-900/50 border-slate-800/50">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <TrendingUp className="h-8 w-8 text-green-500" />
                <div>
                  <p className="text-2xl font-bold text-white">{COMPANY.revenue}</p>
                  <p className="text-sm text-slate-400">CA annuel</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-slate-900/50 border-slate-800/50">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <Database className="h-8 w-8 text-yellow-500" />
                <div>
                  <p className="text-2xl font-bold text-white">{COMPANY.dataSources.length}</p>
                  <p className="text-sm text-slate-400">Sources de données</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="bg-slate-800/50">
            <TabsTrigger value="overview">Vue d'ensemble</TabsTrigger>
            <TabsTrigger value="agents">Agents IA</TabsTrigger>
            <TabsTrigger value="code">Code généré</TabsTrigger>
            <TabsTrigger value="results">Résultats</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6">
              {/* Data Sources */}
              <Card className="bg-slate-900/50 border-slate-800/50">
                <CardHeader>
                  <CardTitle className="text-white flex items-center gap-2">
                    <Database className="h-5 w-5 text-blue-500" />
                    Sources de Données
                  </CardTitle>
                  <CardDescription>Données connectées pour le projet</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {COMPANY.dataSources.map((source) => (
                      <div key={source.id} className="flex items-center justify-between p-3 bg-slate-800/50 rounded-lg">
                        <div className="flex items-center gap-3">
                          {source.type === 'postgresql' && <Database className="h-5 w-5 text-blue-400" />}
                          {source.type === 'shopify' && <ShoppingCart className="h-5 w-5 text-green-400" />}
                          {source.type === 'ga4' && <BarChart3 className="h-5 w-5 text-yellow-400" />}
                          {source.type === 'google_ads' && <PieChart className="h-5 w-5 text-red-400" />}
                          {source.type === 'stripe' && <CreditCard className="h-5 w-5 text-purple-400" />}
                          <div>
                            <p className="text-white font-medium">{source.name}</p>
                            <p className="text-xs text-slate-400">{source.tables} tables • {source.columns} colonnes</p>
                          </div>
                        </div>
                        <Badge variant="outline" className="border-green-500/50 text-green-400">
                          <CheckCircle2 className="h-3 w-3 mr-1" />
                          Connecté
                        </Badge>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Business Objectives */}
              <Card className="bg-slate-900/50 border-slate-800/50">
                <CardHeader>
                  <CardTitle className="text-white flex items-center gap-2">
                    <Zap className="h-5 w-5 text-yellow-500" />
                    Objectifs Business
                  </CardTitle>
                  <CardDescription>Résultats visés par le projet</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {COMPANY.objectives.map((obj, i) => (
                      <div key={i} className="p-3 bg-slate-800/50 rounded-lg">
                        <div className="flex items-center justify-between mb-1">
                          <p className="text-white font-medium">{obj.title}</p>
                          {results && (
                            <Badge className="bg-green-500">Atteint</Badge>
                          )}
                        </div>
                        <p className="text-sm text-slate-400">{obj.description}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="agents" className="space-y-6">
            <Card className="bg-slate-900/50 border-slate-800/50">
              <CardHeader>
                <CardTitle className="text-white">Exécution des Agents IA</CardTitle>
                <CardDescription>
                  Phase {currentPhase}/5 - Les agents collaborent pour générer votre solution
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {agents.map((agent, i) => (
                    <div key={agent.id} className="p-4 bg-slate-800/50 rounded-lg">
                      <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center gap-3">
                          <div className={`p-2 rounded-lg ${
                            agent.status === 'completed' ? 'bg-green-500/20' :
                            agent.status === 'running' ? 'bg-blue-500/20' : 'bg-slate-700'
                          }`}>
                            <agent.icon className={`h-5 w-5 ${
                              agent.status === 'completed' ? 'text-green-500' :
                              agent.status === 'running' ? 'text-blue-500' : 'text-slate-400'
                            }`} />
                          </div>
                          <div>
                            <p className="text-white font-medium">{agent.name}</p>
                            <p className="text-xs text-slate-400">{agent.description}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          {agent.status === 'completed' && (
                            <Badge className="bg-green-500">Terminé</Badge>
                          )}
                          {agent.status === 'running' && (
                            <Badge className="bg-blue-500 animate-pulse">
                              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                              En cours
                            </Badge>
                          )}
                          {agent.status === 'idle' && (
                            <Badge variant="outline" className="border-slate-600">En attente</Badge>
                          )}
                        </div>
                      </div>
                      <Progress value={agent.progress} className="h-2" />
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="code" className="space-y-6">
            <Card className="bg-slate-900/50 border-slate-800/50">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <Code2 className="h-5 w-5 text-blue-500" />
                  Code Généré - dbt Model
                </CardTitle>
                <CardDescription>
                  Modèle customers_360 - Vue unifiée client
                </CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="bg-slate-950 p-4 rounded-lg overflow-x-auto text-sm">
                  <code className="text-slate-300">{SAMPLE_DBT_MODEL}</code>
                </pre>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="results" className="space-y-6">
            {results ? (
              <>
                <div className="grid md:grid-cols-3 gap-4">
                  <Card className="bg-slate-900/50 border-slate-800/50">
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <p className="text-4xl font-bold text-blue-400">{results.models}</p>
                        <p className="text-slate-400">Modèles dbt</p>
                      </div>
                    </CardContent>
                  </Card>
                  <Card className="bg-slate-900/50 border-slate-800/50">
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <p className="text-4xl font-bold text-green-400">{results.dags}</p>
                        <p className="text-slate-400">DAGs Airflow</p>
                      </div>
                    </CardContent>
                  </Card>
                  <Card className="bg-slate-900/50 border-slate-800/50">
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <p className="text-4xl font-bold text-purple-400">{results.tests}</p>
                        <p className="text-slate-400">Tests qualité</p>
                      </div>
                    </CardContent>
                  </Card>
                </div>

                <Card className="bg-slate-900/50 border-slate-800/50">
                  <CardHeader>
                    <CardTitle className="text-white">Résultats Business</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid md:grid-cols-2 gap-6">
                      <div className="space-y-4">
                        <div>
                          <div className="flex justify-between mb-2">
                            <span className="text-slate-400">Score de Qualité</span>
                            <span className="text-green-400 font-bold">{qualityScore}%</span>
                          </div>
                          <Progress value={qualityScore} className="h-3" />
                          <p className="text-xs text-slate-500 mt-1">Amélioration de +22% vs baseline</p>
                        </div>
                        <div>
                          <div className="flex justify-between mb-2">
                            <span className="text-slate-400">Temps de développement</span>
                            <span className="text-blue-400 font-bold">{results.executionTime}</span>
                          </div>
                          <Progress value={14} max={180} className="h-3" />
                          <p className="text-xs text-slate-500 mt-1">vs 6 mois en approche traditionnelle</p>
                        </div>
                      </div>
                      <div className="space-y-3">
                        <div className="p-3 bg-slate-800/50 rounded-lg">
                          <div className="flex items-center justify-between">
                            <span className="text-white">Lignes de code générées</span>
                            <span className="text-blue-400">{results.linesOfCode.toLocaleString()}</span>
                          </div>
                        </div>
                        <div className="p-3 bg-slate-800/50 rounded-lg">
                          <div className="flex items-center justify-between">
                            <span className="text-white">Tables intégrées</span>
                            <span className="text-green-400">{results.tables}</span>
                          </div>
                        </div>
                        <div className="p-3 bg-slate-800/50 rounded-lg">
                          <div className="flex items-center justify-between">
                            <span className="text-white">Économies annuelles estimées</span>
                            <span className="text-yellow-400">150K€</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </>
            ) : (
              <Card className="bg-slate-900/50 border-slate-800/50">
                <CardContent className="py-16 text-center">
                  <Play className="h-16 w-16 mx-auto mb-4 text-slate-600" />
                  <p className="text-slate-400 text-lg">Cliquez sur "Lancer la démo" pour voir les résultats</p>
                </CardContent>
              </Card>
            )}
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
