// AI Data Engineering System - Transformation Agent

import { BaseAgent } from '../core/base-agent';
import type { AgentContext, AgentResult, TransformationConfig } from '../types';

export class TransformationAgent extends BaseAgent {
  constructor() {
    super({
      type: 'transformation',
      name: 'Data Alchemist',
      description: 'Implements data transformations, creates analytical models, and ensures data quality through tests and documentation.',
      systemPrompt: `You are the Transformation Agent for the AI Data Engineering System. Your role is to:

1. **Model Design**: Create dimensional models (facts, dimensions) and data marts
2. **SQL Generation**: Write optimized transformation SQL
3. **Testing**: Implement data quality tests
4. **Documentation**: Generate model documentation

## Modeling Frameworks
- **dbt**: SQL-based transformations with version control
- **Spark**: Large-scale data processing
- **Pandas/DuckDB**: Lightweight transformations

## Model Layers
1. **Staging (stg_)**: Clean and rename source data
2. **Intermediate (int_)**: Join and aggregate
3. **Marts (fct_, dim_)**: Business-ready models

## Best Practices
- Surrogate keys for all dimensions
- SCD Type 2 for historical tracking
- Data quality gates at each layer
- Comprehensive test coverage
- Self-documenting code

## Output Structure
For each transformation:
- Model SQL
- Schema documentation
- Test suite
- Dependencies`,
      capabilities: [
        'Dimensional modeling',
        'SQL optimization',
        'Data quality testing',
        'Documentation generation',
        'Performance tuning',
      ],
    });
  }

  async execute(context: AgentContext, userMessage: string): Promise<AgentResult> {
    const result = await super.execute(context, userMessage);

    if (result.success) {
      // Generate transformation models
      const transformations = await this.generateTransformations(context);
      result.output.transformations = transformations;

      // Add transformation artifacts
      for (const transform of transformations) {
        result.artifacts?.push({
          type: 'sql',
          name: `${transform.name}.sql`,
          content: transform.sql,
          language: 'sql',
        });
      }

      // Add schema documentation
      result.artifacts?.push({
        type: 'document',
        name: 'schema_documentation.md',
        content: this.generateSchemaDocs(transformations),
        language: 'markdown',
      });
    }

    return result;
  }

  private async generateTransformations(context: AgentContext): Promise<TransformationConfig[]> {
    const project = context.projectData;
    const sources = project.dataSources || [];
    const architecture = project.architecture;
    const transformations: TransformationConfig[] = [];

    for (const source of sources) {
      // Staging model
      transformations.push(this.createStagingModel(source));

      // Dimension models
      transformations.push(...this.createDimensionModels(source));

      // Fact models
      transformations.push(this.createFactModel(source));
    }

    return transformations;
  }

  private createStagingModel(source: { id: string; name: string }): TransformationConfig {
    const tableName = source.name.toLowerCase().replace(/\s+/g, '_');
    
    return {
      id: `stg_${tableName}`,
      name: `stg_${tableName}`,
      type: 'staging',
      sourceTables: [`raw.${tableName}`],
      targetTable: `staging.${tableName}`,
      sql: `-- Staging model for ${source.name}
-- Generated by AI Data Engineering System

with source as (
    select * from {{ source('raw', '${tableName}') }}
),

cleaned as (
    select
        -- Remove duplicates
        *,
        row_number() over (partition by id order by loaded_at desc) as _row_num
    from source
),

final as (
    select
        -- Exclude technical columns
        * exclude (_row_num, loaded_at)
    from cleaned
    where _row_num = 1
)

select * from final`,
      tests: [
        { name: 'not_null_id', type: 'not_null', config: { column: 'id' } },
        { name: 'unique_id', type: 'unique', config: { column: 'id' } },
      ],
      documentation: `Staging model for ${source.name}. Cleans and deduplicates raw data.`,
    };
  }

  private createDimensionModels(source: { id: string; name: string }): TransformationConfig[] {
    const tableName = source.name.toLowerCase().replace(/\s+/g, '_');
    
    return [{
      id: `dim_${tableName}`,
      name: `dim_${tableName}`,
      type: 'intermediate',
      sourceTables: [`staging.${tableName}`],
      targetTable: `marts.dim_${tableName}`,
      sql: `-- Dimension model for ${source.name}
-- Generated by AI Data Engineering System

with source as (
    select * from {{ ref('stg_${tableName}') }}
),

hashed as (
    select
        *,
        {{ dbt_utils.generate_surrogate_key(['id']) }} as ${tableName}_key
    from source
)

select
    ${tableName}_key,
    -- Attributes
    id,
    name,
    email,
    status,
    -- Metadata
    created_at,
    updated_at,
    -- SCD Type 2 fields
    current_timestamp as valid_from,
    null::timestamp as valid_to,
    true as is_current
from hashed`,
      tests: [
        { name: 'not_null_key', type: 'not_null', config: { column: `${tableName}_key` } },
        { name: 'unique_key', type: 'unique', config: { column: `${tableName}_key` } },
      ],
      documentation: `Dimension table for ${source.name} with SCD Type 2 tracking.`,
    }];
  }

  private createFactModel(source: { id: string; name: string }): TransformationConfig {
    const tableName = source.name.toLowerCase().replace(/\s+/g, '_');
    
    return {
      id: `fct_${tableName}`,
      name: `fct_${tableName}`,
      type: 'marts',
      sourceTables: [`staging.${tableName}`, `marts.dim_${tableName}`],
      targetTable: `marts.fct_${tableName}`,
      sql: `-- Fact model for ${source.name}
-- Generated by AI Data Engineering System

with source as (
    select * from {{ ref('stg_${tableName}') }}
),

dim as (
    select * from {{ ref('dim_${tableName}') }}
),

joined as (
    select
        source.id,
        dim.${tableName}_key,
        -- Metrics
        source.amount,
        source.quantity,
        -- Timestamps
        source.created_at,
        source.updated_at
    from source
    left join dim on source.id = dim.id
)

select * from joined`,
      tests: [
        { name: 'not_null_key', type: 'not_null', config: { column: `${tableName}_key` } },
        { name: 'relationship_dim', type: 'relationship', config: { from: `${tableName}_key`, to: 'dim', field: `${tableName}_key` } },
      ],
      documentation: `Fact table for ${source.name} transactions.`,
    };
  }

  private generateSchemaDocs(transformations: TransformationConfig[]): string {
    let docs = `# Data Model Documentation\n\n`;
    docs += `Generated by AI Data Engineering System\n\n`;
    docs += `## Overview\n\n`;
    docs += `This document describes the data transformation models.\n\n`;

    docs += `## Model Hierarchy\n\n`;
    docs += `| Model | Type | Source | Target |\n`;
    docs += `|-------|------|--------|--------|\n`;
    
    for (const t of transformations) {
      docs += `| ${t.name} | ${t.type} | ${t.sourceTables.join(', ')} | ${t.targetTable} |\n`;
    }

    docs += `\n## Detailed Models\n\n`;
    
    for (const t of transformations) {
      docs += `### ${t.name}\n\n`;
      docs += `${t.documentation || 'No description available.'}\n\n`;
      docs += `**Tests:**\n`;
      for (const test of t.tests || []) {
        docs += `- ${test.name} (${test.type})\n`;
      }
      docs += `\n`;
    }

    return docs;
  }
}
